  name: Cypress Cloud
  
  on: 
    workflow_dispatch:
      inputs:
        spec:
          description: Run by cypress command line
          default: cypress/e2e/*
  jobs:
    cypress-electron-tests:
      runs-on: ubuntu-latest
      steps:
      - name: Get code
        uses: actions/checkout@v4.1.5
      
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 9c5492e6-584b-4bbd-901c-2cc32cfb35c3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
